date: last-modified

project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "expository-study-notes/**/*.qmd"

website:
  title: "Rong-Kang Zhang"
  description: "Higher category | Grothendieck toposes | Chiral representation theory"
  navbar:
    background: "#023a75ff"
    foreground: "#ffffffff"
    left:
      - text: Expository<br>Study Notes
        icon: journal-text
        menu:
            - text: Overview
              href: expository-study-notes/index.html
            - text: Category theory
              href: expository-study-notes/category-theory/index.html
      - text: "Extemporaneous<br>Reconstruction Talks"
        icon: lightning
        href: extemporaneous-reconstruction/index.qmd
      - text: "Topics to<br>Learn"
        icon : list-check
        href: topics-to-learn/index.html
      - text: Conferences<br>Attended
        icon: calendar-event
        href: conferences-attended/index.html
      - text: Outreach
        href: outreach.qmd
    right:
      - icon: github
        href: https://github.com/valegiunchiglia/
      - icon: twitter
        href: https://twitter.com/valegiunca/
      - icon: envelope
        href: "mailto:v.giunchiglia20@imperial.ac.uk"
      - icon: globe
        href: "mailto:v.giunchiglia20@imperial.ac.uk"
  page-footer:
      left: |
        Made with [Quarto](https://quarto.org/) and managed via [Git](https://git-scm.com/) & [GitHub Desktop](https://desktop.github.com/).
        <br>© 2025 Rong-Kang Zhang · Last updated: {{< meta date >}}

format:
  html:
    theme: 
       light: [cosmo, custom.scss]
       dark:  [darkly, custom.scss]
    toc: true
    linkcolor: blue
    icon:
       source: assets/icons
       name: "zhihu"
       file: "zhihu.svg"
    resources:
        - assets/icons/zhihu.svg



