project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "expository-notes/**/*.qmd"

website:
  title: "Rong-Kang Zhang"
  description: "Higher category | Grothendieck toposes | Chiral representation theory"
  navbar:
    background: "#023a75ff"
    foreground: "#ffffffff"
    left:
      - text: Expository Notes
        href: expository-notes/index.html
      - html : <span>Extemporaneous<br>Reconstruction</span>
        href: extemporaneous-reconstruction/index.qmd
      - text: Conferences Attended
        href: conferences-attended/index.html
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Outreach
        href: outreach.qmd
      - text: CV
        href: curriculum.qmd
    right:
      - icon: github
        href: https://github.com/valegiunchiglia/
      - icon: twitter
        href: https://twitter.com/valegiunca/
      - icon: envelope
        href: "mailto:v.giunchiglia20@imperial.ac.uk"
      - icon: globe
        href: "mailto:v.giunchiglia20@imperial.ac.uk"

format:
  html:
    theme: 
       light: [cosmo, custom.scss]
       dark:  [darkly, custom.scss]
    toc: true
    linkcolor: blue
    icon:
       source: assets/icons
       name: "zhihu"
       file: "zhihu.svg"
    resources:
        - assets/icons/zhihu.svg



