---
title: "👩‍🏫 Teaching"
---

# 2022-23

## Biomedical Research DS stream Workshops
`November - December 22` | **Master's** | [🔗 Materials](https://github.com/valegiunchiglia/Biomedical_Research_DS_stream)

<ul class="horizontal-list">
    <li class="horizontal-list__item horizontal-list__item--teal">Statistics</li>
    <li class="horizontal-list__item horizontal-list__item--blue">R</li>
    <li class="horizontal-list__item horizontal-list__item--grape">ML</li>
</ul>


(Ongoing)

Interactive workshops on a variety of topics in Biomedical Data Science for the MRes Biomedical Research from Imperial College London.

Topics covered so far: Model Validation and Performance & Univariate Statistics.

## Introduction to Computational Methods for the Brain Sciences 
`November 22` | **Master's** | [🔗 Materials](https://github.com/valegiunchiglia/MSc-TranslationalNeuroscience-Module3)

<ul class="horizontal-list">
    <li class="horizontal-list__item horizontal-list__item--yellow">Python</li>
    <li class="horizontal-list__item horizontal-list__item--grape">ML</li>
    <li class="horizontal-list__item horizontal-list__item--teal">Statistics</li>
    <li class="horizontal-list__item horizontal-list__item--imperial-blue">Brain image analysis</li>
    <li class="horizontal-list__item horizontal-list__item--canary">NLP</li>
    <li class="horizontal-list__item horizontal-list__item--coral">Graph Theory</li>
</ul>

I designed the learning materials and assisted in the teaching of all workshops.
Generally speaking, the content included hands-on training in data cleaning, pre-processing and wrangling and applied statistical techniques (i.e. Regression, ANOVA).
More specifically to brain sciences, I designed materials for analysing structural and functional MRI data (i.e. volumetric measures, resting-state, task-fMRI and graph theory). 
Other more advanced workshops that I also created involved hands-on introduction to supervised and unsupervised Machine Learning and NLP.
All workshops materials were shared as Jupyter notebooks.

## Pre-material of the MSc Translational Neuroscience 
`October 22` | **Master's** | [🔗 Materials](https://github.com/valegiunchiglia/MSc-Neuroscience-Python-Course-Development)

<ul class="horizontal-list">
    <li class="horizontal-list__item horizontal-list__item--yellow">Python</li>
</ul>


Coding pre-material of the MSc Translational Neuroscience at Imperial College London.
It is an introduction to programming in Python and statistics, aimed to provide students the necessary foundation to smooothly complete the programming modules that the course offers and to bridge the gap between students with low and high coding literacy.
It contains introductory Jupyter notebooks on all-things Python, including functions, loops, arrays, strings, lists, dictionaries, dataframes, basic statistics (i.e. correlations, t-tests, linear regressions, non-parametric tests) and plotting (both seaborn and matplotlib).

# 2021-22

## Brain imaging
`January - February 22` | **Master's** | [🔗 Materials](https://github.com/valegiunchiglia/personal_website/tree/main/assets/slides/2022-brain-imaging/)

<ul class="horizontal-list">
    <li class="horizontal-list__item horizontal-list__item--imperial-blue">Brain image analysis</li>
</ul>

Teaching of lectures on functional and structural MRI, voxel based morphometry and diffusion tensor imaging. Teaching assistant in the workshops on the practical application of the concepts taught in the lectures.

The lecture slides were prepared with the help from Amy Jolly and Richard Daws.


# 2020-21

## Data Science Helper Team
`October 20 - May 21` | **Master's** | [🔗 Materials](https://github.com/valegiunchiglia/DS_sessions)

<ul class="horizontal-list">
    <li class="horizontal-list__item horizontal-list__item--blue">R</li>
    <li class="horizontal-list__item horizontal-list__item--teal">Statistics</li>
    <li class="horizontal-list__item horizontal-list__item--grape">ML</li>
</ul>


As a lab scientist, what would you do if you need to analyse the data you have collected but you have never done it before?
The DS helper team, which is a **student-led activity** organised within the MRes in Biomedical Research, is **here to help you**.
The project is characterised by different forms of peer-to-peer learning, whose aim is to create an open, friendly, instructive environment where students can reach out in case of issues with data science related topics and can learn some data science if interested.

[Read more](https://blogs.imperial.ac.uk/learning-and-teaching/2021/04/30/student-driven-peer-learning-in-biomedical-data-science/)


# 2019

## Cancer Mehtylome Analysis
`April - August 19` | **Bachelor** | [🔗 Materials](https://github.com/datascience-mobi/05-cancer-genomics)

<ul class="horizontal-list">
    <li class="horizontal-list__item horizontal-list__item--blue">R</li>
    <li class="horizontal-list__item horizontal-list__item--teal">Statistics</li>
</ul>

5 groups of 4 students were tasked with identifying differentially methylateed regions (DMRs) between groups of samples and interpreting the sequence context of these regions. Reducing the dimensionality of the methylation whilst enriching for functionally relevant regions is vital, especially when working with constrained computational resources.
